window.RELIC_PRODUCTS = [
    {
        id: "vinil-ariana-grande",
        category: "vinil",
        title: "Vinil Ariana Grande",
        creatorLabel: "Artista",
        creator: "Ariana Grande",
        price: 120,
        image: "../assets/arianavinil.png",
        summary: "Edicao especial em acabamento premium para colecionadores de pop.",
        details: "Album em vinil com visual marcante, bom estado de conservacao e foco em colecao contemporanea.",
        condition: "Lacrado",
        authenticity: "Certificado pela loja",
        availability: "3 unidades",
        badge: "Edicao especial"
    },
    {
        id: "vinil-taylor-swift",
        category: "vinil",
        title: "Vinil Taylor Swift",
        creatorLabel: "Artista",
        creator: "Taylor Swift",
        price: 145,
        image: "../assets/vinil-taylor-swift.png",
        summary: "Album para colecionadores de pop contemporaneo em edicao elegante.",
        details: "Item procurado por quem gosta de discos recentes com boa apresentacao visual e autenticidade verificada.",
        condition: "Excelente",
        authenticity: "Selo verificado",
        availability: "1 unidade",
        badge: "Raro"
    },
    {
        id: "vinil-elton-john",
        category: "vinil",
        title: "Vinil Elton John",
        creatorLabel: "Artista",
        creator: "Elton John",
        price: 132,
        image: "../assets/disco-de-vinil-elton-john.png",
        summary: "Classico restaurado para compor uma prateleira musical vintage.",
        details: "Disco com apelo nostalgico, autenticidade certificada e foco em quem gosta de artistas atemporais.",
        condition: "Muito bom",
        authenticity: "Certificado pela curadoria",
        availability: "2 unidades",
        badge: "Classico"
    },
    {
        id: "vinil-michael-jackson",
        category: "vinil",
        title: "Vinil Michael Jackson",
        creatorLabel: "Artista",
        creator: "Michael Jackson",
        price: 158,
        image: "../assets/Vinil Michael Jackson.png",
        summary: "Edicao especial pensada para colecoes retro e musica pop classica.",
        details: "Uma opcao forte para quem quer um item reconhecivel, bem apresentado e com verificacao da equipe.",
        condition: "Excelente",
        authenticity: "Verificado pela equipe",
        availability: "4 unidades",
        badge: "Selecao da semana"
    },
    {
        id: "carta-charizard-holo",
        category: "cartas",
        title: "Charizard Holo",
        creatorLabel: "Colecao",
        creator: "Pokemon",
        price: 2500,
        image: "../assets/Charizard Holo-carta.png",
        summary: "Carta rara classica para colecionadores de alto valor afetivo.",
        details: "Item premium com laudo de avaliacao e procura constante entre colecionadores de TCG.",
        condition: "Mint",
        authenticity: "Laudo de avaliacao",
        availability: "1 unidade",
        badge: "Edicao limitada"
    },
    {
        id: "carta-pikachu-illustrator",
        category: "cartas",
        title: "Pikachu Illustrator",
        creatorLabel: "Colecao",
        creator: "Pokemon",
        price: 10000,
        image: "../assets/pikachu-ilustrator-carta.png",
        summary: "Uma das cartas mais desejadas do mercado de colecao.",
        details: "Produto de altissima raridade com autenticidade reforcada por laudo internacional.",
        condition: "Mint",
        authenticity: "Laudo internacional",
        availability: "2 unidades",
        badge: "Raridade maxima"
    },
    {
        id: "carta-mewtwo-gx",
        category: "cartas",
        title: "Mewtwo GX",
        creatorLabel: "Colecao",
        creator: "Pokemon",
        price: 900,
        image: "../assets/Mewtwo GX-carta.png",
        summary: "Peca poderosa e muito procurada entre colecionadores.",
        details: "Carta com boa demanda, autenticidade verificada e perfil ideal para colecoes modernas.",
        condition: "Excelente",
        authenticity: "Verificado pela loja",
        availability: "5 unidades",
        badge: "Classico"
    },
    {
        id: "carta-rayquaza-ex",
        category: "cartas",
        title: "Rayquaza EX",
        creatorLabel: "Colecao",
        creator: "Pokemon",
        price: 1200,
        image: "../assets/Rayquaza EX-carta.png",
        summary: "Item lendario para ampliar uma colecao premium.",
        details: "Carta com visual forte, boa conservacao e perfil de raridade atrativo para colecionadores.",
        condition: "Muito bom",
        authenticity: "Verificado pela curadoria",
        availability: "1 unidade",
        badge: "Raro"
    },
    {
        id: "livro-dom-casmurro",
        category: "livros",
        title: "Dom Casmurro",
        creatorLabel: "Autor",
        creator: "Machado de Assis",
        price: 80,
        image: "../assets/Dom Casmurro-livro.png",
        summary: "Classico brasileiro em edicao de colecionador.",
        details: "Livro com forte valor literario e visual tradicional, ideal para uma biblioteca classica e organizada.",
        condition: "Novo",
        authenticity: "Edicao original",
        availability: "6 unidades",
        badge: "Primeira edicao"
    },
    {
        id: "livro-o-hobbit",
        category: "livros",
        title: "O Hobbit",
        creatorLabel: "Autor",
        creator: "J. R. R. Tolkien",
        price: 95,
        image: "../assets/O Hobbit-livro.png",
        summary: "Aventura fantastica em uma edicao para fa de fantasia.",
        details: "Obra muito buscada por leitores de fantasia, com boa apresentacao e curadoria verificada.",
        condition: "Excelente",
        authenticity: "Curadoria verificada",
        availability: "1 unidade",
        badge: "Raro"
    },
    {
        id: "livro-harry-potter",
        category: "livros",
        title: "Harry Potter",
        creatorLabel: "Autora",
        creator: "J. K. Rowling",
        price: 70,
        image: "../assets/Harry Potter-livro.png",
        summary: "Colecao querida para leitores de varias idades.",
        details: "Livro com apelo nostalgico e boa procura, indicado para quem quer montar uma estante pop e classica.",
        condition: "Muito bom",
        authenticity: "Curadoria verificada",
        availability: "4 unidades",
        badge: "Colecao"
    },
    {
        id: "livro-1984",
        category: "livros",
        title: "1984",
        creatorLabel: "Autor",
        creator: "George Orwell",
        price: 60,
        image: "../assets/1984-livro.png",
        summary: "Distopia indispensavel em uma prateleira de classicos.",
        details: "Livro de leitura direta e impacto duradouro, ideal para quem procura uma obra reconhecida e facil de apresentar no marketplace.",
        condition: "Excelente",
        authenticity: "Edicao original",
        availability: "3 unidades",
        badge: "Primeira edicao"
    },
    {
        id: "jogo-game-boy-advance",
        category: "jogos",
        title: "Game Boy Advance",
        creatorLabel: "Marca",
        creator: "Nintendo",
        price: 400,
        image: "../assets/gameBoyadvance-removebg.png",
        summary: "Console portatil classico da Nintendo.",
        details: "Produto retro com apelo forte para colecionadores e jogadores que valorizam portateis classicos.",
        condition: "Muito bom",
        authenticity: "Verificado pela loja",
        availability: "2 unidades",
        badge: "Classico"
    },
    {
        id: "jogo-super-nintendo",
        category: "jogos",
        title: "Super Nintendo",
        creatorLabel: "Marca",
        creator: "Nintendo",
        price: 400,
        image: "../assets/super nintendo-console.png",
        summary: "Console classico para quem coleciona grandes geracoes dos games.",
        details: "Uma peca muito reconhecida do universo retro, com apelo nostalgico e boa leitura visual na vitrine.",
        condition: "Muito bom",
        authenticity: "Verificado pela loja",
        availability: "3 unidades",
        badge: "Classico"
    },
    {
        id: "jogo-atari-2600",
        category: "jogos",
        title: "Atari 2600",
        creatorLabel: "Marca",
        creator: "Atari",
        price: 550,
        image: "../assets/atari.png",
        summary: "Um dos consoles mais simbolicos da historia dos games.",
        details: "Peca importante para qualquer colecao retro, com visual reconhecivel e alta carga nostalgica.",
        condition: "Muito bom",
        authenticity: "Curadoria verificada",
        availability: "2 unidades",
        badge: "Retro"
    },
    {
        id: "jogo-nintendinho",
        category: "jogos",
        title: "Nintendinho",
        creatorLabel: "Marca",
        creator: "Nintendo",
        price: 1499,
        image: "../assets/nintendinho.png",
        summary: "Console 8 bits que revolucionou os games.",
        details: "Produto de alto interesse para colecionadores que buscam marcos importantes da historia dos videogames.",
        condition: "Excelente",
        authenticity: "Verificado pela equipe",
        availability: "1 unidade",
        badge: "Raro"
    },
    {
        id: "jogo-game-boy-color",
        category: "jogos",
        title: "Game Boy Color",
        creatorLabel: "Marca",
        creator: "Nintendo",
        price: 1000,
        image: "../assets/gameboycolor.png",
        summary: "Versao colorida do classico portatil.",
        details: "Item retro que combina nostalgia, portabilidade e valor de colecao em um mesmo produto.",
        condition: "Excelente",
        authenticity: "Verificado pela loja",
        availability: "2 unidades",
        badge: "Edicao especial"
    }
];
